In [1]:
import numpy as np 
import pandas as pd

In [2]:
books=pd.read_csv('datasets/books.csv')
users=pd.read_csv('datasets/users.csv')
ratings=pd.read_csv('datasets/ratings.csv')

C:\Users\Emon Karmoker\AppData\Local\Temp\ipykernel_25664\3541263927.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books=pd.read_csv('datasets/books.csv')

In [3]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [4]:
users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [5]:
ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [6]:
books.shape

(271360, 8)

In [7]:
ratings.shape

(1149780, 3)

In [8]:
users.shape

(278858, 3)

In [9]:
books.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            2
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [10]:
books.duplicated().sum()

0

In [11]:
ratings_with_name=ratings .merge(books,on='ISBN')

In [12]:
num_rating_df=ratings_with_name.groupby('Book-Title').count()['Book-Rating'].reset_index()
num_rating_df.rename(columns={'Book-Rating':'num-ratings'},inplace=True)

In [13]:
avg_rating_df = ratings_with_name.groupby('Book-Title')['Book-Rating'].mean().reset_index()

avg_rating_df.rename(columns={'Book-Rating':'avg-ratings'},inplace=True)

In [14]:
avg_rating_df

                                               Book-Title  avg-ratings
0        A Light in the Storm: The Civil War Diary of ...     2.250000
1                                   Always Have Popsicles     0.000000
2                    Apple Magic (The Collector's series)     0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...     8.000000
4        Beyond IBM: Leadership Marketing and Finance ...     0.000000
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.     0.000000
241067                     Ã?Â?rger mit Produkt X. Roman.     5.250000
241068                                Ã?Â?sterlich leben.     7.000000
241069                              Ã?Â?stlich der Berge.     2.666667
241070                                  Ã?Â?thique en toc     4.000000

[241071 rows x 2 columns]

In [15]:
popular_df=num_rating_df.merge(avg_rating_df,on='Book-Title')
popular_df

,Book-Title,num-ratings,avg-ratings
0,A Light in the Storm: The Civil War Diary of ...,4,2.250000
1,Always Have Popsicles,1,0.000000
2,Apple Magic (The Collector's series),1,0.000000
3,"Ask Lily (Young Women of Faith: Lily Series, ...",1,8.000000
4,Beyond IBM: Leadership Marketing and Finance ...,1,0.000000
...,...,...,...
241066,Ã?Â?lpiraten.,2,0.000000
241067,Ã?Â?rger mit Produkt X. Roman.,4,5.250000
241068,Ã?Â?sterlich leben.,1,7.000000
241069,Ã?Â?stlich der Berge.,3,2.666667
241070,Ã?Â?thique en toc,2,4.000000

In [16]:
popular_df=popular_df[popular_df['num-ratings']>=250].sort_values('avg-ratings',ascending=False).head(50)

In [17]:
popular_df=popular_df.merge(books,on='Book-Title').drop_duplicates('Book-Title')[['Book-Title','Book-Author','Image-URL-M','avg-ratings']]

In [18]:
x=ratings_with_name.groupby('User-ID').count()['Book-Rating'] > 200
padhe_likhe_users=x[x].index

In [19]:
filtered_rating=ratings_with_name[ratings_with_name['User-ID'].isin(padhe_likhe_users)]

In [20]:
y=filtered_rating.groupby('Book-Title').count()['Book-Rating']>=50
famous_books=y[y].index

In [33]:
final_ratings=filtered_rating[filtered_rating['Book-Title'].isin(famous_books)]

In [76]:
pt

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Bend in the Road,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0

In [77]:
pt=final_ratings.pivot_table(index='Book-Title',columns='User-ID',values='Book-Rating')

In [79]:
pt.fillna(0,inplace=True)

In [80]:
from sklearn.metrics.pairwise import cosine_similarity

In [81]:
similarity_scores=cosine_similarity(pt)

In [82]:
similarity_scores
type(similarity_scores)

numpy.ndarray

In [83]:
similarity_scores
len(similarity_scores)
similarity_scores[0]

array([1.        , 0.10255025, 0.01220856, 0.        , 0.05367224,
       0.02774901, 0.08216491, 0.13732869, 0.03261686, 0.03667591,
       0.02322418, 0.06766487, 0.02083978, 0.09673735, 0.13388865,
       0.08303112, 0.11153543, 0.05100411, 0.02517784, 0.11706383,
       0.        , 0.14333793, 0.07847534, 0.06150451, 0.08723968,
       0.        , 0.07009814, 0.13658681, 0.07600328, 0.12167134,
       0.00768046, 0.01473221, 0.        , 0.07965814, 0.04522617,
       0.01556271, 0.09495938, 0.0182307 , 0.02610465, 0.07984012,
       0.11679969, 0.0569124 , 0.08354155, 0.08471898, 0.08785938,
       0.05491435, 0.0548505 , 0.27026514, 0.09779123, 0.06016046,
       0.08958835, 0.06748675, 0.        , 0.04468098, 0.01920872,
       0.        , 0.05629067, 0.00557964, 0.07877059, 0.05219479,
       0.18908177, 0.        , 0.01240656, 0.02984572, 0.04279502,
       0.12680125, 0.16566735, 0.        , 0.13357242, 0.06615478,
       0.        , 0.        , 0.        , 0.10968075, 0.02806606,
       0.04521795, 0.02613277, 0.06876131, 0.01331627, 0.10519138,
       0.03349457, 0.01363458, 0.23669374, 0.        , 0.10397941,
       0.06167753, 0.14176273, 0.11661083, 0.08331012, 0.00850895,
       0.06715433, 0.        , 0.15850821, 0.0328052 , 0.01068915,
       0.02579782, 0.02114859, 0.02687779, 0.02175821, 0.        ,
       0.01601663, 0.12114266, 0.04768603, 0.05819184, 0.06510722,
       0.        , 0.0476705 , 0.05273165, 0.0281001 , 0.06524573,
       0.02116345, 0.02097868, 0.07422249, 0.01752778, 0.03734567,
       0.        , 0.01579666, 0.11039448, 0.16527277, 0.15514319,
       0.06237454, 0.08139489, 0.05655414, 0.07458203, 0.03771888,
       0.0593633 , 0.02955369, 0.03355603, 0.04734093, 0.01006643,
       0.01671982, 0.07258935, 0.        , 0.        , 0.        ,
       0.02428501, 0.03067819, 0.0997498 , 0.        , 0.01690152,
       0.02410862, 0.0281084 , 0.        , 0.        , 0.01812877,
       0.02880827, 0.        , 0.05995157, 0.02127671, 0.1034119 ,
       0.02766748, 0.10684795, 0.09898722, 0.14145186, 0.05007429,
       0.09428289, 0.01411249, 0.        , 0.07835976, 0.00882242,
       0.04515898, 0.        , 0.01281412, 0.04003334, 0.07477661,
       0.01217906, 0.01887393, 0.02667484, 0.01432864, 0.14702847,
       0.06087282, 0.02578321, 0.02741876, 0.        , 0.14909595,
       0.05606788, 0.        , 0.03199916, 0.03643817, 0.        ,
       0.01962921, 0.22222254, 0.01515845, 0.09673268, 0.02190023,
       0.02013549, 0.05400331, 0.07262017, 0.01111637, 0.03649872,
       0.05994664, 0.        , 0.14691167, 0.02086005, 0.10359635,
       0.09794375, 0.06609997, 0.12871083, 0.08992739, 0.01147457,
       0.02460165, 0.        , 0.18049207, 0.05141892, 0.0477174 ,
       0.10849696, 0.13278139, 0.05915288, 0.05372984, 0.034785  ,
       0.        , 0.09203039, 0.06388401, 0.04773328, 0.15570975,
       0.08420691, 0.12338217, 0.0878469 , 0.08205945, 0.12177532,
       0.02433703, 0.00272862, 0.        , 0.        , 0.03671505,
       0.15280984, 0.0370943 , 0.07458136, 0.09746697, 0.05416091,
       0.10266993, 0.07574414, 0.06426526, 0.0360174 , 0.01559752,
       0.02033559, 0.02463593, 0.        , 0.03349154, 0.02135369,
       0.0190337 , 0.06806265, 0.02032116, 0.11784706, 0.07839488,
       0.08422558, 0.        , 0.02040796, 0.        , 0.04698246,
       0.08294513, 0.13974514, 0.01234525, 0.13510608, 0.07423489,
       0.11841889, 0.04930091, 0.01621668, 0.02633023, 0.04815972,
       0.01959826, 0.10174253, 0.13257638, 0.        , 0.0551027 ,
       0.0186115 , 0.        , 0.04504598, 0.03482459, 0.16503292,
       0.08466191, 0.06795353, 0.02987653, 0.        , 0.        ,
       0.08781993, 0.07885279, 0.04799058, 0.01467964, 0.02123837,
       0.04549923, 0.08673969, 0.00885998, 0.02880637, 0.02022145,
       0.02414122, 0.12548312, 0.        , 0.02482518, 0.06520606,
       0.        , 0.0606983 , 0.01177824, 0.13974105, 0.01978844,
       0.01260824, 0.08608601, 0.04433883, 0.02943085, 0.02242496,
       0.06541868, 0.07866868, 0.14281399, 0.11979305, 0.01858409,
       0.13445377, 0.04809338, 0.09790644, 0.        , 0.17415731,
       0.07437756, 0.        , 0.12389065, 0.01042391, 0.02580849,
       0.        , 0.0895139 , 0.04005551, 0.19182231, 0.02267512,
       0.01730347, 0.03054044, 0.07008822, 0.10084626, 0.10467615,
       0.01683462, 0.12468283, 0.10266459, 0.03549836, 0.02667484,
       0.07652765, 0.08474056, 0.01831977, 0.02177482, 0.15293362,
       0.        , 0.        , 0.01063251, 0.02153089, 0.02946443,
       0.        , 0.02076783, 0.01194825, 0.00953675, 0.2067554 ,
       0.01554292, 0.0390266 , 0.06681046, 0.09014973, 0.05914735,
       0.06206857, 0.        , 0.02005959, 0.07843566, 0.16337845,
       0.07161075, 0.        , 0.14595258, 0.07561631, 0.02939738,
       0.04779629, 0.01807238, 0.11362722, 0.09791273, 0.07999693,
       0.08912337, 0.10941777, 0.        , 0.02115842, 0.0600393 ,
       0.01797154, 0.05755408, 0.02166863, 0.09754449, 0.13107652,
       0.        , 0.06829904, 0.09132922, 0.        , 0.02781406,
       0.01533368, 0.06113179, 0.01757286, 0.02471294, 0.0180158 ,
       0.11789806, 0.06468143, 0.13904191, 0.        , 0.06671644,
       0.        , 0.        , 0.05762086, 0.02266096, 0.00844876,
       0.02297481, 0.07136276, 0.15305514, 0.06039874, 0.        ,
       0.08996912, 0.01545947, 0.10135299, 0.        , 0.01676344,
       0.        , 0.0502188 , 0.16041182, 0.        , 0.13439733,
       0.12508514, 0.02329035, 0.0198727 , 0.01105674, 0.02548034,
       0.00896044, 0.08246122, 0.01902896, 0.07025003, 0.0216367 ,
       0.12822982, 0.09998772, 0.08642895, 0.06355197, 0.02883024,
       0.04335826, 0.0470659 , 0.05223733, 0.        , 0.08982751,
       0.00875634, 0.09923542, 0.10228551, 0.        , 0.12307492,
       0.01758929, 0.02028125, 0.1033827 , 0.13028171, 0.08988894,
       0.09005001, 0.05332049, 0.08033436, 0.04597795, 0.06139888,
       0.02300709, 0.02304904, 0.06523041, 0.01915363, 0.        ,
       0.04542766, 0.        , 0.        , 0.05261954, 0.01317088,
       0.        , 0.        , 0.0485931 , 0.0734819 , 0.10354481,
       0.01718807, 0.09919937, 0.08091989, 0.00358835, 0.04757132,
       0.11122765, 0.05143481, 0.0566614 , 0.        , 0.06087719,
       0.10800615, 0.        , 0.07554686, 0.        , 0.13644384,
       0.04796763, 0.16104067, 0.        , 0.01759864, 0.05438295,
       0.        , 0.08100801, 0.13090711, 0.00581844, 0.07150547,
       0.05428487, 0.06143184, 0.05161653, 0.1951182 , 0.1149488 ,
       0.06513047, 0.06401961, 0.        , 0.        , 0.10853662,
       0.11400426, 0.0463925 , 0.01825277, 0.        , 0.01195201,
       0.21057744, 0.05809707, 0.04349156, 0.02646256, 0.07276403,
       0.05264857, 0.07242165, 0.06790898, 0.01626564, 0.02431809,
       0.02093565, 0.13617057, 0.11784149, 0.08588206, 0.09284352,
       0.11277297, 0.06868983, 0.08200947, 0.13369059, 0.        ,
       0.19972625, 0.02286207, 0.0806288 , 0.        , 0.05756015,
       0.06738056, 0.        , 0.19656288, 0.06306426, 0.03499381,
       0.06123119, 0.09596456, 0.02180168, 0.02317515, 0.06476149,
       0.07052241, 0.08280452, 0.1700872 , 0.07213921, 0.01172201,
       0.08541218, 0.17990898, 0.08007284, 0.01739625, 0.16728777,
       0.26396194, 0.1840891 , 0.05600273, 0.04133586, 0.06911015,
       0.14456847, 0.22626397, 0.19208896, 0.0239334 , 0.20025064,
       0.01507653, 0.05144282, 0.1233368 , 0.1420166 , 0.02472079,
       0.08563805, 0.02363426, 0.12794024, 0.01083153, 0.07352436,
       0.09532519, 0.03421895, 0.07194212, 0.02297079, 0.15344079,
       0.08856302, 0.        , 0.        , 0.01878656, 0.09772942,
       0.04404359, 0.15211972, 0.0152225 , 0.10307399, 0.05715789,
       0.04600056, 0.06303899, 0.06572303, 0.14421331, 0.08272478,
       0.        , 0.04203701, 0.02276077, 0.17381829, 0.01909967,
       0.16000268, 0.14681486, 0.        , 0.05940546, 0.07725115,
       0.07464763, 0.06546696, 0.07021577, 0.18921368, 0.02494136,
       0.01705027, 0.05437622, 0.04932819, 0.        , 0.11445399,
       0.08001595, 0.12858515, 0.02306658, 0.06129105, 0.02090769,
       0.04550867, 0.1026659 , 0.10725982, 0.0260534 , 0.00173709,
       0.0987294 , 0.08077482, 0.02159226, 0.01614275, 0.0208464 ,
       0.09797466, 0.01906731, 0.18571699, 0.05344577, 0.18925314,
       0.05894189, 0.01488161, 0.1202478 , 0.09840359, 0.01048126,
       0.10596224, 0.07617195, 0.0805439 , 0.        , 0.23299389,
       0.01073642, 0.13573542, 0.04578552, 0.14440017, 0.        ,
       0.12522954, 0.0645501 , 0.02817522, 0.14445559, 0.01721045,
       0.09508161, 0.0517902 , 0.18410818, 0.08704224, 0.10990764,
       0.10850377, 0.03954865, 0.0383631 , 0.02463491, 0.07845405,
       0.03455548, 0.03007681, 0.02484076, 0.04223674, 0.14444517,
       0.12340234, 0.01510201, 0.0284437 , 0.02132016, 0.07391778,
       0.08904276, 0.15893871, 0.06947574, 0.01060787, 0.        ,
       0.09993169, 0.05711356, 0.09488374, 0.00948943, 0.13365876,
       0.05794064, 0.        , 0.06721284, 0.02066998, 0.        ,
       0.01839428, 0.        , 0.12655364, 0.08418288, 0.09095705,
       0.00730589, 0.08143881, 0.        , 0.04218803, 0.08392849,
       0.07785801, 0.        , 0.07151794, 0.02407593, 0.01635126,
       0.03734567, 0.05237227, 0.01140169, 0.00968725, 0.12530648,
       0.00909905, 0.05864096, 0.01769644, 0.12110367, 0.07347567,
       0.04316046])

In [104]:
def recommend(book_name):
    index= np.where(pt.index==book_name)[0][0]
    similar_items=sorted(list(enumerate(similarity_scores[index])), key=lambda x: x[1], reverse=True)[1:6]
    for i in similar_items:
        print(pt.index[i[0]])

In [108]:
recommend('Message in a Bottle')

Nights in Rodanthe
The Mulberry Tree
A Walk to Remember
River's End
Nightmares &amp; Dreamscapes

In [103]:
np.where(pt.index=='Zoya')[0][0]

704

In [86]:
similarity_scores[0]

array([1.        , 0.10255025, 0.01220856, 0.        , 0.05367224,
       0.02774901, 0.08216491, 0.13732869, 0.03261686, 0.03667591,
       0.02322418, 0.06766487, 0.02083978, 0.09673735, 0.13388865,
       0.08303112, 0.11153543, 0.05100411, 0.02517784, 0.11706383,
       0.        , 0.14333793, 0.07847534, 0.06150451, 0.08723968,
       0.        , 0.07009814, 0.13658681, 0.07600328, 0.12167134,
       0.00768046, 0.01473221, 0.        , 0.07965814, 0.04522617,
       0.01556271, 0.09495938, 0.0182307 , 0.02610465, 0.07984012,
       0.11679969, 0.0569124 , 0.08354155, 0.08471898, 0.08785938,
       0.05491435, 0.0548505 , 0.27026514, 0.09779123, 0.06016046,
       0.08958835, 0.06748675, 0.        , 0.04468098, 0.01920872,
       0.        , 0.05629067, 0.00557964, 0.07877059, 0.05219479,
       0.18908177, 0.        , 0.01240656, 0.02984572, 0.04279502,
       0.12680125, 0.16566735, 0.        , 0.13357242, 0.06615478,
       0.        , 0.        , 0.        , 0.10968075, 0.02806606,
       0.04521795, 0.02613277, 0.06876131, 0.01331627, 0.10519138,
       0.03349457, 0.01363458, 0.23669374, 0.        , 0.10397941,
       0.06167753, 0.14176273, 0.11661083, 0.08331012, 0.00850895,
       0.06715433, 0.        , 0.15850821, 0.0328052 , 0.01068915,
       0.02579782, 0.02114859, 0.02687779, 0.02175821, 0.        ,
       0.01601663, 0.12114266, 0.04768603, 0.05819184, 0.06510722,
       0.        , 0.0476705 , 0.05273165, 0.0281001 , 0.06524573,
       0.02116345, 0.02097868, 0.07422249, 0.01752778, 0.03734567,
       0.        , 0.01579666, 0.11039448, 0.16527277, 0.15514319,
       0.06237454, 0.08139489, 0.05655414, 0.07458203, 0.03771888,
       0.0593633 , 0.02955369, 0.03355603, 0.04734093, 0.01006643,
       0.01671982, 0.07258935, 0.        , 0.        , 0.        ,
       0.02428501, 0.03067819, 0.0997498 , 0.        , 0.01690152,
       0.02410862, 0.0281084 , 0.        , 0.        , 0.01812877,
       0.02880827, 0.        , 0.05995157, 0.02127671, 0.1034119 ,
       0.02766748, 0.10684795, 0.09898722, 0.14145186, 0.05007429,
       0.09428289, 0.01411249, 0.        , 0.07835976, 0.00882242,
       0.04515898, 0.        , 0.01281412, 0.04003334, 0.07477661,
       0.01217906, 0.01887393, 0.02667484, 0.01432864, 0.14702847,
       0.06087282, 0.02578321, 0.02741876, 0.        , 0.14909595,
       0.05606788, 0.        , 0.03199916, 0.03643817, 0.        ,
       0.01962921, 0.22222254, 0.01515845, 0.09673268, 0.02190023,
       0.02013549, 0.05400331, 0.07262017, 0.01111637, 0.03649872,
       0.05994664, 0.        , 0.14691167, 0.02086005, 0.10359635,
       0.09794375, 0.06609997, 0.12871083, 0.08992739, 0.01147457,
       0.02460165, 0.        , 0.18049207, 0.05141892, 0.0477174 ,
       0.10849696, 0.13278139, 0.05915288, 0.05372984, 0.034785  ,
       0.        , 0.09203039, 0.06388401, 0.04773328, 0.15570975,
       0.08420691, 0.12338217, 0.0878469 , 0.08205945, 0.12177532,
       0.02433703, 0.00272862, 0.        , 0.        , 0.03671505,
       0.15280984, 0.0370943 , 0.07458136, 0.09746697, 0.05416091,
       0.10266993, 0.07574414, 0.06426526, 0.0360174 , 0.01559752,
       0.02033559, 0.02463593, 0.        , 0.03349154, 0.02135369,
       0.0190337 , 0.06806265, 0.02032116, 0.11784706, 0.07839488,
       0.08422558, 0.        , 0.02040796, 0.        , 0.04698246,
       0.08294513, 0.13974514, 0.01234525, 0.13510608, 0.07423489,
       0.11841889, 0.04930091, 0.01621668, 0.02633023, 0.04815972,
       0.01959826, 0.10174253, 0.13257638, 0.        , 0.0551027 ,
       0.0186115 , 0.        , 0.04504598, 0.03482459, 0.16503292,
       0.08466191, 0.06795353, 0.02987653, 0.        , 0.        ,
       0.08781993, 0.07885279, 0.04799058, 0.01467964, 0.02123837,
       0.04549923, 0.08673969, 0.00885998, 0.02880637, 0.02022145,
       0.02414122, 0.12548312, 0.        , 0.02482518, 0.06520606,
       0.        , 0.0606983 , 0.01177824, 0.13974105, 0.01978844,
       0.01260824, 0.08608601, 0.04433883, 0.02943085, 0.02242496,
       0.06541868, 0.07866868, 0.14281399, 0.11979305, 0.01858409,
       0.13445377, 0.04809338, 0.09790644, 0.        , 0.17415731,
       0.07437756, 0.        , 0.12389065, 0.01042391, 0.02580849,
       0.        , 0.0895139 , 0.04005551, 0.19182231, 0.02267512,
       0.01730347, 0.03054044, 0.07008822, 0.10084626, 0.10467615,
       0.01683462, 0.12468283, 0.10266459, 0.03549836, 0.02667484,
       0.07652765, 0.08474056, 0.01831977, 0.02177482, 0.15293362,
       0.        , 0.        , 0.01063251, 0.02153089, 0.02946443,
       0.        , 0.02076783, 0.01194825, 0.00953675, 0.2067554 ,
       0.01554292, 0.0390266 , 0.06681046, 0.09014973, 0.05914735,
       0.06206857, 0.        , 0.02005959, 0.07843566, 0.16337845,
       0.07161075, 0.        , 0.14595258, 0.07561631, 0.02939738,
       0.04779629, 0.01807238, 0.11362722, 0.09791273, 0.07999693,
       0.08912337, 0.10941777, 0.        , 0.02115842, 0.0600393 ,
       0.01797154, 0.05755408, 0.02166863, 0.09754449, 0.13107652,
       0.        , 0.06829904, 0.09132922, 0.        , 0.02781406,
       0.01533368, 0.06113179, 0.01757286, 0.02471294, 0.0180158 ,
       0.11789806, 0.06468143, 0.13904191, 0.        , 0.06671644,
       0.        , 0.        , 0.05762086, 0.02266096, 0.00844876,
       0.02297481, 0.07136276, 0.15305514, 0.06039874, 0.        ,
       0.08996912, 0.01545947, 0.10135299, 0.        , 0.01676344,
       0.        , 0.0502188 , 0.16041182, 0.        , 0.13439733,
       0.12508514, 0.02329035, 0.0198727 , 0.01105674, 0.02548034,
       0.00896044, 0.08246122, 0.01902896, 0.07025003, 0.0216367 ,
       0.12822982, 0.09998772, 0.08642895, 0.06355197, 0.02883024,
       0.04335826, 0.0470659 , 0.05223733, 0.        , 0.08982751,
       0.00875634, 0.09923542, 0.10228551, 0.        , 0.12307492,
       0.01758929, 0.02028125, 0.1033827 , 0.13028171, 0.08988894,
       0.09005001, 0.05332049, 0.08033436, 0.04597795, 0.06139888,
       0.02300709, 0.02304904, 0.06523041, 0.01915363, 0.        ,
       0.04542766, 0.        , 0.        , 0.05261954, 0.01317088,
       0.        , 0.        , 0.0485931 , 0.0734819 , 0.10354481,
       0.01718807, 0.09919937, 0.08091989, 0.00358835, 0.04757132,
       0.11122765, 0.05143481, 0.0566614 , 0.        , 0.06087719,
       0.10800615, 0.        , 0.07554686, 0.        , 0.13644384,
       0.04796763, 0.16104067, 0.        , 0.01759864, 0.05438295,
       0.        , 0.08100801, 0.13090711, 0.00581844, 0.07150547,
       0.05428487, 0.06143184, 0.05161653, 0.1951182 , 0.1149488 ,
       0.06513047, 0.06401961, 0.        , 0.        , 0.10853662,
       0.11400426, 0.0463925 , 0.01825277, 0.        , 0.01195201,
       0.21057744, 0.05809707, 0.04349156, 0.02646256, 0.07276403,
       0.05264857, 0.07242165, 0.06790898, 0.01626564, 0.02431809,
       0.02093565, 0.13617057, 0.11784149, 0.08588206, 0.09284352,
       0.11277297, 0.06868983, 0.08200947, 0.13369059, 0.        ,
       0.19972625, 0.02286207, 0.0806288 , 0.        , 0.05756015,
       0.06738056, 0.        , 0.19656288, 0.06306426, 0.03499381,
       0.06123119, 0.09596456, 0.02180168, 0.02317515, 0.06476149,
       0.07052241, 0.08280452, 0.1700872 , 0.07213921, 0.01172201,
       0.08541218, 0.17990898, 0.08007284, 0.01739625, 0.16728777,
       0.26396194, 0.1840891 , 0.05600273, 0.04133586, 0.06911015,
       0.14456847, 0.22626397, 0.19208896, 0.0239334 , 0.20025064,
       0.01507653, 0.05144282, 0.1233368 , 0.1420166 , 0.02472079,
       0.08563805, 0.02363426, 0.12794024, 0.01083153, 0.07352436,
       0.09532519, 0.03421895, 0.07194212, 0.02297079, 0.15344079,
       0.08856302, 0.        , 0.        , 0.01878656, 0.09772942,
       0.04404359, 0.15211972, 0.0152225 , 0.10307399, 0.05715789,
       0.04600056, 0.06303899, 0.06572303, 0.14421331, 0.08272478,
       0.        , 0.04203701, 0.02276077, 0.17381829, 0.01909967,
       0.16000268, 0.14681486, 0.        , 0.05940546, 0.07725115,
       0.07464763, 0.06546696, 0.07021577, 0.18921368, 0.02494136,
       0.01705027, 0.05437622, 0.04932819, 0.        , 0.11445399,
       0.08001595, 0.12858515, 0.02306658, 0.06129105, 0.02090769,
       0.04550867, 0.1026659 , 0.10725982, 0.0260534 , 0.00173709,
       0.0987294 , 0.08077482, 0.02159226, 0.01614275, 0.0208464 ,
       0.09797466, 0.01906731, 0.18571699, 0.05344577, 0.18925314,
       0.05894189, 0.01488161, 0.1202478 , 0.09840359, 0.01048126,
       0.10596224, 0.07617195, 0.0805439 , 0.        , 0.23299389,
       0.01073642, 0.13573542, 0.04578552, 0.14440017, 0.        ,
       0.12522954, 0.0645501 , 0.02817522, 0.14445559, 0.01721045,
       0.09508161, 0.0517902 , 0.18410818, 0.08704224, 0.10990764,
       0.10850377, 0.03954865, 0.0383631 , 0.02463491, 0.07845405,
       0.03455548, 0.03007681, 0.02484076, 0.04223674, 0.14444517,
       0.12340234, 0.01510201, 0.0284437 , 0.02132016, 0.07391778,
       0.08904276, 0.15893871, 0.06947574, 0.01060787, 0.        ,
       0.09993169, 0.05711356, 0.09488374, 0.00948943, 0.13365876,
       0.05794064, 0.        , 0.06721284, 0.02066998, 0.        ,
       0.01839428, 0.        , 0.12655364, 0.08418288, 0.09095705,
       0.00730589, 0.08143881, 0.        , 0.04218803, 0.08392849,
       0.07785801, 0.        , 0.07151794, 0.02407593, 0.01635126,
       0.03734567, 0.05237227, 0.01140169, 0.00968725, 0.12530648,
       0.00909905, 0.05864096, 0.01769644, 0.12110367, 0.07347567,
       0.04316046])

In [ ]:
similar_items=sorted(list(enumerate(similarity_scores[0])), key=lambda x: x[1], reverse=True)

[(0, 0.9999999999999998),
 (47, 0.2702651417103732),
 (545, 0.2639619371123497),
 (82, 0.23669374347400993),
 (634, 0.23299389358170394),
 (551, 0.2262639743141286),
 (181, 0.22222254415660225),
 (500, 0.21057743765309012),
 (344, 0.20675540390453995),
 (554, 0.20025063706783053),
 (520, 0.19972624710300058),
 (527, 0.19656287691544358),
 (488, 0.19511819825564608),
 (552, 0.1920889620576415),
 (318, 0.19182230688281934),
 (624, 0.1892531370760997),
 (598, 0.189213677823462),
 (60, 0.18908176672188648),
 (622, 0.18571699439818884),
 (647, 0.1841081817659337),
 (546, 0.18408910419891056),
 (202, 0.18049207281616433),
 (541, 0.17990898085771034),
 (309, 0.17415730924332484),
 (588, 0.1738182944100774),
 (537, 0.1700871998622835),
 (544, 0.1672877700938274),
 (66, 0.16566734565340116),
 (118, 0.165272766123669),
 (269, 0.1650329228149958),
 (354, 0.16337845332530374),
 (476, 0.16104067376144765),
 (407, 0.16041182196659062),
 (590, 0.16000267935045498),
 (666, 0.1589387141616799),
 (92, 0.15850821182810643),
 (214, 0.15570975499937129),
 (119, 0.15514318804365945),
 (569, 0.15344079020689355),
 (397, 0.1530551446766823),
 (334, 0.15293362041446346),
 (225, 0.1528098402276361),
 (576, 0.15211972188253267),
 (174, 0.14909595195082756),
 (169, 0.14702846562277322),
 (192, 0.14691166711955864),
 (591, 0.14681485749917436),
 (357, 0.1459525808785892),
 (550, 0.1445684727872654),
 (643, 0.1444555917585842),
 (659, 0.14444516556944695),
 (638, 0.14440017099395475),
 (583, 0.14421330855040418),
 (21, 0.14333792815336935),
 (302, 0.1428139852200272),
 (558, 0.1420165983985733),
 (86, 0.1417627291694863),
 (153, 0.14145186155692357),
 (251, 0.13974513728492968),
 (293, 0.13974104783917973),
 (387, 0.1390419059870689),
 (7, 0.13732869060263378),
 (27, 0.13658680855472938),
 (474, 0.13644383961641227),
 (511, 0.13617057407600314),
 (636, 0.13573542468856645),
 (253, 0.1351060763800879),
 (305, 0.13445376799866068),
 (409, 0.1343973311768824),
 (14, 0.13388864701187034),
 (518, 0.13369059478865902),
 (674, 0.13365875731715246),
 (68, 0.13357242093379193),
 (206, 0.1327813903167589),
 (262, 0.13257638388225185),
 (374, 0.13107651944057502),
 (482, 0.13090710604063543),
 (438, 0.130281708532021),
 (197, 0.12871083086643306),
 (606, 0.12858515029485706),
 (420, 0.12822981990037824),
 (562, 0.1279402426979562),
 (65, 0.12680124740531368),
 (682, 0.1265536444037226),
 (286, 0.12548312467838352),
 (699, 0.12530648498478347),
 (640, 0.12522954271046702),
 (410, 0.12508513698245888),
 (326, 0.12468283384023092),
 (312, 0.1238906533021012),
 (660, 0.12340233502840114),
 (216, 0.12338216998991305),
 (557, 0.12333680291383342),
 (434, 0.12307492189941618),
 (219, 0.12177532243608828),
 (29, 0.12167133598776536),
 (101, 0.12114265984279052),
 (703, 0.12110366748083307),
 (627, 0.12024780353669523),
 (303, 0.11979305199464946),
 (255, 0.1184188929166314),
 (385, 0.1178980615083171),
 (243, 0.11784705785247843),
 (512, 0.11784149206441577),
 (19, 0.11706383185253948),
 (40, 0.11679968613719668),
 (87, 0.11661082872914152),
 (489, 0.1149487959814155),
 (604, 0.1144539948977886),
 (495, 0.11400426236261282),
 (362, 0.11362722122094872),
 (515, 0.11277296885857815),
 (16, 0.1115354275858341),
 (465, 0.11122764671322921),
 (117, 0.1103944810687539),
 (649, 0.1099076405115528),
 (73, 0.1096807501418389),
 (366, 0.10941777035919222),
 (494, 0.10853661984252007),
 (650, 0.10850377176901972),
 (205, 0.10849696385128585),
 (470, 0.10800615252570414),
 (612, 0.10725981836116358),
 (151, 0.10684794535545848),
 (630, 0.10596223905942811),
 (79, 0.10519138203342883),
 (324, 0.10467615354986062),
 (84, 0.10397940924207362),
 (194, 0.1035963528100001),
 (459, 0.10354480865656568),
 (149, 0.10341190148072846),
 (437, 0.1033826953037451),
 (578, 0.10307399310158656),
 (230, 0.10266993316420167),
 (611, 0.10266590131312461),
 (327, 0.10266459423639845),
 (1, 0.10255024829874466),
 (432, 0.10228551050235933),
 (261, 0.10174252819190155),
 (402, 0.10135299399598713),
 (323, 0.10084626149563478),
 (421, 0.0999877199669616),
 (670, 0.09993168845101595),
 (137, 0.09974980034668827),
 (431, 0.09923541776574221),
 (461, 0.09919937023309428),
 (152, 0.09898722239993361),
 (615, 0.0987294045857185),
 (628, 0.09840359079895453),
 (620, 0.09797466122629746),
 (195, 0.09794374510256892),
 (363, 0.09791273187403501),
 (307, 0.09790644477767069),
 (48, 0.09779122591837028),
 (574, 0.09772941568150427),
 (373, 0.09754449459555777),
 (228, 0.09746696979819942),
 (13, 0.09673734976610586),
 (183, 0.09673267751838878),
 (531, 0.09596456280564838),
 (565, 0.09532519178944057),
 (645, 0.09508161331593905),
 (36, 0.09495937740802216),
 (672, 0.09488374038474037),
 (155, 0.09428288870384942),
 (514, 0.0928435169211848),
 (211, 0.09203038690315052),
 (377, 0.09132921952528268),
 (684, 0.09095705260744957),
 (348, 0.09014973218560088),
 (440, 0.09005001295005992),
 (400, 0.08996912406728536),
 (198, 0.08992738703666601),
 (439, 0.08988894455657523),
 (429, 0.08982750671022352),
 (50, 0.08958834926611466),
 (316, 0.08951389572154368),
 (365, 0.0891233745026412),
 (665, 0.08904275766583061),
 (570, 0.0885630163776942),
 (44, 0.08785938150991274),
 (217, 0.08784690368235953),
 (275, 0.08781992709390865),
 (24, 0.08723968326958673),
 (648, 0.08704223712018071),
 (281, 0.08673968616705958),
 (422, 0.08642894687915843),
 (296, 0.08608600626732467),
 (513, 0.08588206473402643),
 (560, 0.08563805381851426),
 (540, 0.08541217689607684),
 (331, 0.08474055728984814),
 (43, 0.08471898090442946),
 (270, 0.08466191294337998),
 (245, 0.08422557655984436),
 (215, 0.08420691059370962),
 (683, 0.08418288167449578),
 (689, 0.0839284865111645),
 (42, 0.08354155383339157),
 (88, 0.08331012208964667),
 (15, 0.0830311169181103),
 (250, 0.08294512991462386),
 (536, 0.08280451731096075),
 (584, 0.08272478073987326),
 (416, 0.0824612198578452),
 (6, 0.08216491130000354),
 (218, 0.08205944603394638),
 (517, 0.08200947294838494),
 (686, 0.08143881222401984),
 (121, 0.08139488796880032),
 (481, 0.08100800937525751),
 (462, 0.08091989315700655),
 (616, 0.0807748212690039),
 (522, 0.08062879942666365),
 (632, 0.0805438980307519),
 (442, 0.08033435626539932),
 (542, 0.08007284499901246),
 (605, 0.08001595368794218),
 (364, 0.07999692625971765),
 (39, 0.07984012108659384),
 (33, 0.07965814289647455),
 (276, 0.07885279086963545),
 (58, 0.07877058635507732),
 (301, 0.07866868132289853),
 (22, 0.07847534327232125),
 (654, 0.07845404559691257),
 (353, 0.07843565693314272),
 (244, 0.07839488163675291),
 (158, 0.07835976130061303),
 (690, 0.07785800873431292),
 (594, 0.07725115117942094),
 (330, 0.07652764821891074),
 (631, 0.07617194789896939),
 (28, 0.07600327535501017),
 (231, 0.0757441443938586),
 (358, 0.07561631141753603),
 (472, 0.0755468596127809),
 (164, 0.07477661367406771),
 (595, 0.07464762808145006),
 (123, 0.07458202717929566),
 (227, 0.07458136399603107),
 (310, 0.07437756212042423),
 (254, 0.07423488726781508),
 (112, 0.07422249010392888),
 (664, 0.07391777683093743),
 (564, 0.07352435567112062),
 (458, 0.07348190409223959),
 (704, 0.07347566833900478),
 (504, 0.07276403383736725),
 (187, 0.07262017448772083),
 (131, 0.07258934796997447),
 (506, 0.07242165076731459),
 (538, 0.07213921021695388),
 (567, 0.0719421185191427),
 (355, 0.07161075491687474),
 (692, 0.07151793939760115),
 (484, 0.07150547342980032),
 (396, 0.07136276113078666),
 (535, 0.07052240553428667),
 (418, 0.07025002832914887),
 (597, 0.07021576771146076),
 (26, 0.07009814362931202),
 (322, 0.0700882246357741),
 (667, 0.06947573726333098),
 (549, 0.0691101496608291),
 (77, 0.06876130890656589),
 (516, 0.06868983304237651),
 (376, 0.06829903941402894),
 (241, 0.06806264765162154),
 (271, 0.06795352889900172),
 (507, 0.06790897506872169),
 (11, 0.06766486753662343),
 (51, 0.06748675491514017),
 (525, 0.06738056011305654),
 (677, 0.0672128392842741),
 (90, 0.06715432766232284),
 (347, 0.06681045925540752),
 (389, 0.06671644037106779),
 (69, 0.06615478064452682),
 (196, 0.06609996896203728),
 (582, 0.06572303470837207),
 (596, 0.06546695823953794),
 (300, 0.06541867556977009),
 (109, 0.06524573363186935),
 (447, 0.06523041320455897),
 (289, 0.06520605980064662),
 (490, 0.06513046875777172),
 (104, 0.06510721558252526),
 (534, 0.06476148889541151),
 (386, 0.06468143253238315),
 (641, 0.06455010070487521),
 (232, 0.06426525769208898),
 (491, 0.06401961292305569),
 (212, 0.06388401351716998),
 (423, 0.0635519690782283),
 (528, 0.06306425554305625),
 (581, 0.06303898971663935),
 (120, 0.06237453600241552),
 (350, 0.06206857320564754),
 (85, 0.06167753120046458),
 (23, 0.06150451339525138),
 (486, 0.06143184266443724),
 (444, 0.061398875647666676),
 (608, 0.06129105448105361),
 (530, 0.06123118935155921),
 (381, 0.06113178628791212),
 (469, 0.060877194204984726),
 (170, 0.06087281632872059),
 (291, 0.06069830203664196),
 (398, 0.06039873575147915),
 (49, 0.060160461842087495),
 (369, 0.060039300152930415),
 (147, 0.05995157134958024),
 (190, 0.05994663767295999),
 (593, 0.05940546334243634),
 (125, 0.059363300295016304),
 (207, 0.059152881703632795),
 (349, 0.05914734917065386),
 (625, 0.05894189200911533),
 (701, 0.05864096359154978),
 (103, 0.058191840680734276),
 (501, 0.058097069301565475),
 (675, 0.057940637804840725),
 (392, 0.057620863815487075),
 (524, 0.057560148077814344),
 (371, 0.05755407693373189),
 (579, 0.057157891413611744),
 (671, 0.05711356172333468),
 (41, 0.056912401804646934),
 (467, 0.05666140304625101),
 (122, 0.056554138733275305),
 (56, 0.05629066845910846),
 (175, 0.05606788035530558),
 (547, 0.05600272988869),
 (264, 0.055102704646119355),
 (45, 0.05491435163039676),
 (46, 0.054850498513470236),
 (479, 0.05438295377092604),
 (601, 0.05437622462310082),
 (485, 0.05428487095514969),
 (229, 0.05416091103251691),
 (186, 0.05400331245399732),
 (208, 0.053729841666378134),
 (4, 0.053672244225442485),
 (623, 0.053445774200822666),
 (441, 0.05332049434044375),
 (107, 0.05273164983675109),
 (505, 0.05264856975654457),
 (453, 0.05261953990010256),
 (696, 0.05237226614377158),
 (427, 0.0522373263993224),
 (59, 0.052194792200893965),
 (646, 0.05179020017229585),
 (487, 0.051616531477964966),
 (556, 0.05144282019851702),
 (466, 0.051434806536338154),
 (203, 0.05141892092902459),
 (17, 0.05100410510067514),
 (406, 0.05021880312673623),
 (154, 0.05007429159938883),
 (602, 0.04932819154504025),
 (256, 0.049300912125160704),
 (457, 0.048593102089385304),
 (259, 0.04815971759587031),
 (306, 0.04809338200514574),
 (277, 0.04799058127298857),
 (475, 0.04796762686649386),
 (360, 0.047796293241950796),
 (213, 0.04773328410790857),
 (204, 0.047717402129725514),
 (102, 0.04768602689229997),
 (106, 0.047670497142785574),
 (464, 0.04757132169040053),
 (128, 0.04734092759216691),
 (426, 0.04706590154362337),
 (249, 0.046982457315643385),
 (496, 0.046392498261486066),
 (580, 0.046000562607200646),
 (443, 0.045977952103493924),
 (637, 0.045785523306335146),
 (610, 0.04550867061591275),
 (280, 0.04549923467689111),
 (450, 0.04542765998492866),
 (34, 0.04522616573040869),
 (75, 0.04521795287053612),
 (160, 0.04515898041752436),
 (267, 0.04504597870526374),
 (53, 0.044680983219421905),
 (297, 0.04433882752568145),
 (575, 0.044043586511889346),
 (502, 0.043491562429456586),
 (425, 0.04335826491498011),
 (705, 0.04316045784191231),
 (64, 0.04279501979786338),
 (658, 0.04223674045619745),
 (688, 0.042188025333763236),
 (586, 0.04203701143606598),
 (548, 0.04133585716291763),
 (317, 0.04005551020725377),
 (163, 0.04003333547158616),
 (651, 0.03954864515701187),
 (346, 0.03902659506471766),
 (652, 0.03836309816637586),
 (124, 0.03771888280719047),
 (114, 0.03734566872286401),
 (695, 0.03734566872286401),
 (226, 0.03709430441334803),
 (224, 0.03671505063990275),
 (9, 0.03667590746512177),
 (189, 0.036498718026030004),
 (178, 0.03643816906953526),
 (233, 0.03601739518550193),
 (328, 0.035498355256648746),
 (529, 0.03499381360818396),
 (268, 0.03482458685305275),
 (209, 0.034785003361519164),
 (655, 0.03455547895208963),
 (566, 0.03421894679431926),
 (127, 0.03355602562283),
 (80, 0.03349456939792139),
 (238, 0.03349154464789058),
 (93, 0.03280520241000348),
 (8, 0.03261686350494277),
 (177, 0.03199916313406436),
 (136, 0.030678189040978528),
 (321, 0.03054044240047009),
 (656, 0.030076807297674774),
 (272, 0.029876534978291205),
 (63, 0.029845724311982225),
 (126, 0.02955369248311012),
 (339, 0.02946442510264468),
 (298, 0.029430847399312027),
 (359, 0.029397384230560795),
 (424, 0.028830240654024085),
 (145, 0.028808272598853126),
 (283, 0.028806369616477166),
 (662, 0.028443700563612766),
 (642, 0.02817521704586765),
 (141, 0.028108399645259814),
 (108, 0.02810009706063171),
 (74, 0.02806606106883051),
 (379, 0.02781406274224919),
 (5, 0.027749013024662858),
 (150, 0.027667475691473428),
 (172, 0.027418756526771074),
 (97, 0.02687778911799567),
 (167, 0.026674838717939867),
 (329, 0.026674838717939867),
 (503, 0.02646255704581015),
 (258, 0.026330228561191004),
 (76, 0.02613276804655889),
 (38, 0.026104653172312028),
 (613, 0.026053401473749117),
 (314, 0.025808491020821493),
 (95, 0.025797824097510556),
 (171, 0.025783211586063344),
 (414, 0.025480338679592467),
 (18, 0.025177841632809915),
 (599, 0.02494136129371724),
 (657, 0.024840764583155147),
 (288, 0.02482518222135733),
 (559, 0.024720785609384784),
 (383, 0.024712941476041382),
 (236, 0.024635927968282654),
 (653, 0.02463490862737704),
 (200, 0.024601653277066596),
 (220, 0.024337026385897676),
 (509, 0.024318094429406693),
 (135, 0.02428501142412964),
 (285, 0.024141217209915328),
 (140, 0.024108621631248803),
 (693, 0.02407593195976403),
 (553, 0.023933399289577127),
 (561, 0.023634261138311616),
 (411, 0.02329035016031528),
 (10, 0.02322418425912186),
 (533, 0.023175154774464087),
 (607, 0.023066582966561253),
 (446, 0.023049037833599993),
 (445, 0.023007092325074995),
 (395, 0.02297481006625077),
 (568, 0.022970785411852147),
 (521, 0.0228620664348094),
 (587, 0.022760772453994885),
 (319, 0.02267512161790004),
 (393, 0.02266096293926825),
 (299, 0.022424955017243866),
 (184, 0.02190023295408395),
 (532, 0.021801683645525486),
 (333, 0.021774817728178283),
 (98, 0.02175821065382328),
 (372, 0.021668631362692693),
 (419, 0.021636698437203145),
 (617, 0.02159225803102367),
 (338, 0.021530886296301118),
 (239, 0.021353685011361416),
 (663, 0.021320163671431275),
 (148, 0.021276714965680187),
 (279, 0.021238372796229556),
 (110, 0.021163446843373374),
 (368, 0.02115842407200956),
 (96, 0.02114858980511902),
 (111, 0.02097867986921867),
 (510, 0.020935646634428463),
 (609, 0.02090768582511093),
 (193, 0.020860053643757807),
 (619, 0.020846396819831855),
 (12, 0.020839782065795794),
 (341, 0.020767833514212724),
 (678, 0.020669978441948792),
 (247, 0.02040796206066411),
 (235, 0.02033558874805688),
 (242, 0.020321161226731627),
 (436, 0.020281245334279798),
 (284, 0.020221447157344582),
 (185, 0.020135489410098205),
 (352, 0.020059585724360268),
 (412, 0.019872703940133213),
 (294, 0.019788442258843547),
 (180, 0.01962921144060071),
 (260, 0.019598256153707194),
 (54, 0.019208718234636258),
 (448, 0.01915362558614925),
 (589, 0.019099672781938637),
 (621, 0.019067312487474012),
 (240, 0.019033695446023926),
 (417, 0.01902896010686717),
 (166, 0.018873932015163516),
 (573, 0.018786559700050654),
 (265, 0.018611497829688243),
 (304, 0.01858409288796079),
 (680, 0.018394279624570017),
 (332, 0.018319772326554337),
 (497, 0.018252769789423258),
 (37, 0.018230696811058135),
 (144, 0.0181287703514146),
 (361, 0.018072383204619496),
 (384, 0.018015801292409934),
 (370, 0.017971540540139944),
 (702, 0.017696441246693336),
 (478, 0.017598641856748937),
 (435, 0.01758928833928951),
 (382, 0.017572862308732076),
 (113, 0.017527779718968118),
 (543, 0.017396246144706713),
 (320, 0.017303468493582226),
 (644, 0.017210453378914768),
 (460, 0.0171880657878069),
 (600, 0.017050265851722604),
 (139, 0.016901518597837405),
 (325, 0.016834621675675482),
 (404, 0.016763442237401817),
 (130, 0.016719816747289874),
 (694, 0.016351262734144115),
 (508, 0.016265641643564675),
 (257, 0.016216682151444957),
 (618, 0.016142753550857224),
 (100, 0.016016629607635186),
 (116, 0.01579666260459111),
 (234, 0.01559751952620105),
 (35, 0.01556270914112474),
 (345, 0.015542921836058245),
 (401, 0.015459465622161536),
 (380, 0.015333681815045101),
 (577, 0.015222501642298877),
 (182, 0.015158449197584845),
 (661, 0.015102006885841438),
 (555, 0.015076532862248153),
 (626, 0.014881608648267744),
 (31, 0.01473221255132234),
 (278, 0.014679640011206505),
 (168, 0.01432863977616057),
 (156, 0.014112489355409683),
 (81, 0.013634576553468258),
 (78, 0.013316271087745269),
 (454, 0.01317087876205714),
 (162, 0.012814117802391826),
 (295, 0.012608239194211564),
 (62, 0.012406560213354146),
 (252, 0.012345246102533871),
 (2, 0.012208555646509366),
 (165, 0.012179056920074677),
 (499, 0.011952011165403655),
 (342, 0.011948245768325256),
 (292, 0.011778242975805127),
 (539, 0.011722012964226876),
 (199, 0.011474570339750256),
 (697, 0.011401692977613393),
 (188, 0.011116365315772406),
 (413, 0.011056735115042383),
 (563, 0.01083152786792504),
 (635, 0.01073641547918824),
 (94, 0.010689154840164533),
 (337, 0.010632508151830204),
 (668, 0.010607867311865709),
 (629, 0.010481255663709239),
 (313, 0.010423913217045038),
 (129, 0.010066425112509755),
 (698, 0.009687245558530464),
 (343, 0.009536746594659161),
 (673, 0.009489432211152974),
 (700, 0.009099054369341325),
 (415, 0.0089604367821904),
 (282, 0.00885998445194921),
 (159, 0.00882242400686552),
 (430, 0.00875634332679306),
 (89, 0.00850895140653615),
 (394, 0.008448763927099017),
 (30, 0.007680459111722776),
 (685, 0.007305889033771798),
 (483, 0.00581843892000093),
 (57, 0.005579638588454276),
 (463, 0.0035883533320389396),
 (221, 0.00272862336930817),
 (614, 0.0017370894470936135),
 (3, 0.0),
 (20, 0.0),
 (25, 0.0),
 (32, 0.0),
 (52, 0.0),
 (55, 0.0),
 (61, 0.0),
 (67, 0.0),
 (70, 0.0),
 (71, 0.0),
 (72, 0.0),
 (83, 0.0),
 (91, 0.0),
 (99, 0.0),
 (105, 0.0),
 (115, 0.0),
 (132, 0.0),
 (133, 0.0),
 (134, 0.0),
 (138, 0.0),
 (142, 0.0),
 (143, 0.0),
 (146, 0.0),
 (157, 0.0),
 (161, 0.0),
 (173, 0.0),
 (176, 0.0),
 (179, 0.0),
 (191, 0.0),
 (201, 0.0),
 (210, 0.0),
 (222, 0.0),
 (223, 0.0),
 (237, 0.0),
 (246, 0.0),
 (248, 0.0),
 (263, 0.0),
 (266, 0.0),
 (273, 0.0),
 (274, 0.0),
 (287, 0.0),
 (290, 0.0),
 (308, 0.0),
 (311, 0.0),
 (315, 0.0),
 (335, 0.0),
 (336, 0.0),
 (340, 0.0),
 (351, 0.0),
 (356, 0.0),
 (367, 0.0),
 (375, 0.0),
 (378, 0.0),
 (388, 0.0),
 (390, 0.0),
 (391, 0.0),
 (399, 0.0),
 (403, 0.0),
 (405, 0.0),
 (408, 0.0),
 (428, 0.0),
 (433, 0.0),
 (449, 0.0),
 (451, 0.0),
 (452, 0.0),
 (455, 0.0),
 (456, 0.0),
 (468, 0.0),
 (471, 0.0),
 (473, 0.0),
 (477, 0.0),
 (480, 0.0),
 (492, 0.0),
 (493, 0.0),
 (498, 0.0),
 (519, 0.0),
 (523, 0.0),
 (526, 0.0),
 (571, 0.0),
 (572, 0.0),
 (585, 0.0),
 (592, 0.0),
 (603, 0.0),
 (633, 0.0),
 (639, 0.0),
 (669, 0.0),
 (676, 0.0),
 (679, 0.0),
 (681, 0.0),
 (687, 0.0),
 (691, 0.0)]